#!/bin/bash


echo "HTTP/1.0 200 OK"
echo "Content-Type: Image/png"
echo


# For example - interpret the user request and generate web page from that:
read request
option=$(echo "$request" | cut -d ' ' -f 2)

case "$option" in
    (/image/)
		cat image.png
	:;
esac
